main.banner-mode: off

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=challenge
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  kafka:
    properties:
      schema.registry.url: http://localhost:9081
    client-id: orders-service
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      auto.register.schema: true
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
logging:
  level:
    org:
      hibernate:
        SQL: debug

order.event.destinationTopic.OrderCreatedEvent: order_created_event



kafka:
  bootstrap-servers: http://localhost:9092
  schema-registry-url: http://localhost:9081
  request.timeout: 30000
